apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: second_fastapi:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000